#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MaterialDialogs.Sample.Resource", IsApplication=true)]

namespace MaterialDialogs.Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040000
			public const int Items = 2130968576;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int Basic = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int Callback = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int DIcon = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int Input = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int List = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int LongBtn = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int Multip = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int Progress = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int Single = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int ThreeButton = 2131099651;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int Agree = 2131034112;
			
			// aapt resource value: 0x7f05000f
			public const int ApplicationName = 2131034127;
			
			// aapt resource value: 0x7f050001
			public const int Cancel = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int Content = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int Ignore = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int LongPositive = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int WithBasic = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int WithCallback = 2131034121;
			
			// aapt resource value: 0x7f050006
			public const int WithIcon = 2131034118;
			
			// aapt resource value: 0x7f05000d
			public const int WithInput = 2131034125;
			
			// aapt resource value: 0x7f05000a
			public const int WithList = 2131034122;
			
			// aapt resource value: 0x7f050007
			public const int WithLongButton = 2131034119;
			
			// aapt resource value: 0x7f05000c
			public const int WithMultip = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int WithProgress = 2131034126;
			
			// aapt resource value: 0x7f05000b
			public const int WithSingle = 2131034123;
			
			// aapt resource value: 0x7f050008
			public const int WithThreeButton = 2131034120;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
